INSERT INTO
    users (username, email, password_hash)
VALUES
    (
        'admin',
        'admin@example.com',
        'hashed_password_here'
    ),
    (
        'user1',
        'user1@example.com',
        'hashed_password_here'
    ),
    (
        'user2',
        'user2@example.com',
        'hashed_password_here'
    ),
    (
        'user3',
        'user3@example.com',
        'hashed_password_here'
    ),
    (
        'user4',
        'user4@example.com',
        'hashed_password_here'
    ),
    (
        'user5',
        'user5@example.com',
        'hashed_password_here'
    ),
    (
        'user6',
        'user6@example.com',
        'hashed_password_here'
    ),
    (
        'user7',
        'user7@example.com',
        'hashed_password_here'
    ),
    (
        'user8',
        'user8@example.com',
        'hashed_password_here'
    ),
    (
        'user9',
        'user9@example.com',
        'hashed_password_here'
    ),
    (
        'user10',
        'user10@example.com',
        'hashed_password_here'
    ),
    (
        'user11',
        'user11@example.com',
        'hashed_password_here'
    ),
    (
        'user12',
        'user12@example.com',
        'hashed_password_here'
    ),
    (
        'user13',
        'user13@example.com',
        'hashed_password_here'
    ),
    (
        'user14',
        'user14@example.com',
        'hashed_password_here'
    ),
    (
        'user15',
        'user15@example.com',
        'hashed_password_here'
    ),
    (
        'user16',
        'user16@example.com',
        'hashed_password_here'
    ),
    (
        'user17',
        'user17@example.com',
        'hashed_password_here'
    ),
    (
        'user18',
        'user18@example.com',
        'hashed_password_here'
    ),
    (
        'user19',
        'user19@example.com',
        'hashed_password_here'
    ),
    (
        'user20',
        'user20@example.com',
        'hashed_password_here'
    ),
    (
        'user21',
        'user21@example.com',
        'hashed_password_here'
    ),
    (
        'user22',
        'user22@example.com',
        'hashed_password_here'
    ),
    (
        'user23',
        'user23@example.com',
        'hashed_password_here'
    ),
    (
        'user24',
        'user24@example.com',
        'hashed_password_here'
    ),
    (
        'user25',
        'user25@example.com',
        'hashed_password_here'
    ),
    (
        'user26',
        'user26@example.com',
        'hashed_password_here'
    ),
    (
        'user27',
        'user27@example.com',
        'hashed_password_here'
    ),
    (
        'user28',
        'user28@example.com',
        'hashed_password_here'
    ),
    (
        'user29',
        'user29@example.com',
        'hashed_password_here'
    ),
    (
        'user30',
        'user30@example.com',
        'hashed_password_here'
    ),
    (
        'user31',
        'user31@example.com',
        'hashed_password_here'
    ),
    (
        'user32',
        'user32@example.com',
        'hashed_password_here'
    ),
    (
        'user33',
        'user33@example.com',
        'hashed_password_here'
    ),
    (
        'user34',
        'user34@example.com',
        'hashed_password_here'
    ),
    (
        'user35',
        'user35@example.com',
        'hashed_password_here'
    ),
    (
        'user36',
        'user36@example.com',
        'hashed_password_here'
    ),
    (
        'user37',
        'user37@example.com',
        'hashed_password_here'
    ),
    (
        'user38',
        'user38@example.com',
        'hashed_password_here'
    ),
    (
        'user39',
        'user39@example.com',
        'hashed_password_here'
    ),
    (
        'user40',
        'user40@example.com',
        'hashed_password_here'
    ),
    (
        'user41',
        'user41@example.com',
        'hashed_password_here'
    ),
    (
        'user42',
        'user42@example.com',
        'hashed_password_here'
    ),
    (
        'user43',
        'user43@example.com',
        'hashed_password_here'
    ),
    (
        'user44',
        'user44@example.com',
        'hashed_password_here'
    ),
    (
        'user45',
        'user45@example.com',
        'hashed_password_here'
    ),
    (
        'user46',
        'user46@example.com',
        'hashed_password_here'
    ),
    (
        'user47',
        'user47@example.com',
        'hashed_password_here'
    ),
    (
        'user48',
        'user48@example.com',
        'hashed_password_here'
    ),
    (
        'user49',
        'user49@example.com',
        'hashed_password_here'
    ),
    (
        'user50',
        'user50@example.com',
        'hashed_password_here'
    ),
    (
        'user51',
        'user51@example.com',
        'hashed_password_here'
    ),
    (
        'user52',
        'user52@example.com',
        'hashed_password_here'
    ),
    (
        'user53',
        'user53@example.com',
        'hashed_password_here'
    ),
    (
        'user54',
        'user54@example.com',
        'hashed_password_here'
    ),
    (
        'user55',
        'user55@example.com',
        'hashed_password_here'
    ),
    (
        'user56',
        'user56@example.com',
        'hashed_password_here'
    ),
    (
        'user57',
        'user57@example.com',
        'hashed_password_here'
    ),
    (
        'user58',
        'user58@example.com',
        'hashed_password_here'
    ),
    (
        'user59',
        'user59@example.com',
        'hashed_password_here'
    ),
    (
        'user60',
        'user60@example.com',
        'hashed_password_here'
    ),
    (
        'user61',
        'user61@example.com',
        'hashed_password_here'
    ),
    (
        'user62',
        'user62@example.com',
        'hashed_password_here'
    ),
    (
        'user63',
        'user63@example.com',
        'hashed_password_here'
    ),
    (
        'user64',
        'user64@example.com',
        'hashed_password_here'
    ),
    (
        'user65',
        'user65@example.com',
        'hashed_password_here'
    ),
    (
        'user66',
        'user66@example.com',
        'hashed_password_here'
    ),
    (
        'user67',
        'user67@example.com',
        'hashed_password_here'
    ),
    (
        'user68',
        'user68@example.com',
        'hashed_password_here'
    ),
    (
        'user69',
        'user69@example.com',
        'hashed_password_here'
    ),
    (
        'user70',
        'user70@example.com',
        'hashed_password_here'
    ),
    (
        'user71',
        'user71@example.com',
        'hashed_password_here'
    ),
    (
        'user72',
        'user72@example.com',
        'hashed_password_here'
    ),
    (
        'user73',
        'user73@example.com',
        'hashed_password_here'
    ),
    (
        'user74',
        'user74@example.com',
        'hashed_password_here'
    ),
    (
        'user75',
        'user75@example.com',
        'hashed_password_here'
    ),
    (
        'user76',
        'user76@example.com',
        'hashed_password_here'
    ),
    (
        'user77',
        'user77@example.com',
        'hashed_password_here'
    ),
    (
        'user78',
        'user78@example.com',
        'hashed_password_here'
    ),
    (
        'user79',
        'user79@example.com',
        'hashed_password_here'
    ),
    (
        'user80',
        'user80@example.com',
        'hashed_password_here'
    ),
    (
        'user81',
        'user81@example.com',
        'hashed_password_here'
    ),
    (
        'user82',
        'user82@example.com',
        'hashed_password_here'
    ),
    (
        'user83',
        'user83@example.com',
        'hashed_password_here'
    ),
    (
        'user84',
        'user84@example.com',
        'hashed_password_here'
    ),
    (
        'user85',
        'user85@example.com',
        'hashed_password_here'
    ),
    (
        'user86',
        'user86@example.com',
        'hashed_password_here'
    ),
    (
        'user87',
        'user87@example.com',
        'hashed_password_here'
    ),
    (
        'user88',
        'user88@example.com',
        'hashed_password_here'
    ),
    (
        'user89',
        'user89@example.com',
        'hashed_password_here'
    ),
    (
        'user90',
        'user90@example.com',
        'hashed_password_here'
    ),
    (
        'user91',
        'user91@example.com',
        'hashed_password_here'
    ),
    (
        'user92',
        'user92@example.com',
        'hashed_password_here'
    ),
    (
        'user93',
        'user93@example.com',
        'hashed_password_here'
    ),
    (
        'user94',
        'user94@example.com',
        'hashed_password_here'
    ),
    (
        'user95',
        'user95@example.com',
        'hashed_password_here'
    ),
    (
        'user96',
        'user96@example.com',
        'hashed_password_here'
    ),
    (
        'user97',
        'user97@example.com',
        'hashed_password_here'
    ),
    (
        'user98',
        'user98@example.com',
        'hashed_password_here'
    ),
    (
        'user99',
        'user99@example.com',
        'hashed_password_here'
    ),
    (
        'user100',
        'user100@example.com',
        'hashed_password_here'
    );